name: "volatility with ubuntu CI workflow"


on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:

  volatility-ubuntu-ubuntu-latest-job:
    name: "build volatility with ubuntu 16.04 on ubuntu latest"
    runs-on: ubuntu-latest
    env:
      version: "latest"
      name: "ubuntu/volatility"
      dockerfiledir: "dockerfiles"
      dockerfilename: "Dockerfile.ubuntu.volatility"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch                  
    - name: "build volatility with ubuntu"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not usedi
        set -xe
        whoami
        echo ${USER} 
        #Add current logged in user to the docker group.
        sudo usermod -aG docker ${USER}
        id  ${USER}
        docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version} 
        docker system df -v               
        docker image inspect ${name}:${version}  
        echo "################## ENTRYPOINT ##################"
        docker inspect -f '{{.Config.Entrypoint}}' ${name}:${version}
        echo "################## ENTRYPOINT ##################"
        docker run ${name}:${version} -h  
    - name: "analyze with volatility"
      run: |
        docker image ls
        sudo apt-get install megatools p7zip -y
        #download image 
        megadl 'https://mega.nz/#!sh8wmCIL!b4tpech4wzc3QQ6YgQ2uZnOmctRZ2duQxDqxbkWYipQ'
        sleep 10
        p7zip -d OtterCTF.7z
        sleep 10
        du -h OtterCTF.vmem && mv OtterCTF.vmem /tmp
        docker run -v /tmp:/tmp ubuntu/volatility:latest -f /tmp/OtterCTF.vmem imageinfo